### ISSUE TITLE
Week 5 Meeting Minutes

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#63]
## Updates
Sho
- Documentation for LSTM, pushed to branch
- Prediction data is ready, pushed to repo

Gretel 
- PowerPoint slides done up till hyperparameter

Sophia (branch: 44)
- RNN
- Tried to run LSTM through CV function, but could not run the complex LSTM through CV function
- Multilayer RNN currently most accurate within RNN for RMSE and MAE, for both validation and test
- Shared plot of prediction for salmon in Canada Pacific

Sam (branch: model-development)
- XGBoost tuning
- Lowest RMSE: 7.56 after tuning
- Model saved as pickle with CV results also saved in csv
- Plot of salmon in canada, actual vs predicted, table for different XGBoost models
- XGBoost not very good at predicting outlier prices

## To dos
Sho
- Plot salmon until 2100 to see how models perform
- Consider tests or start merging important files to main/organise repo (with Gretel)

Gretel
- Will continue working on that and agenda for morning and early afternoon, open to suggestion for late afternoon
- Consider tests or start merging important files to main/organise repo (with Sho)

Sophia
- Check on code to make sure there is no leakage
- Might do tuning for RNN since there is a chance we will use it for final model

Sam
- Plot NN plot of price for salmon

**Comment by sho-i98** [comment]
## Update
Sam:
- Plots and Table (NN and XGBoost) ready to show the partner.
- NN is predicting the same values, maybe the values converges to the same value because val-error went up and early stopping condition met, needs further investigation.
Gretel: 
- Slides and agenda ready for the meetings
Sho:
- Unusual observations in predictions with XGBoost, RNN, LSTM - all the predictions are predicting around the mean
- Significant variabilities observed in the predicted tonnes data
Sophia:
- Multi-layer LSTM defined, but multi-layer RNN is still the winning model.
- The training process to modify later .

## Todo's 
- Discuss the predictions made upto end of the century
- Repo clean up strategies

**Comment by fohy24** [comment]
## Decide What to Do

- Clean up and documentation
- Organize repo like readme
- Discuss dashboard
- Presentation prep – make a template

Alexi will share the grading rubric by the end of next week.

Wait for the rubric before cleaning up?  
We can work on the dashboard now.  
Tests can wait until next week because we don’t have many functions in XGBoost.

## Decide Which Platform to Build the Dashboard

### Suggestions

- Tableau
- Streamlit

Tableau has a free version, but it's uncertain if the partner needs a paid/Tableau account to access.  
Go with Tableau for now.

## Tasks

- Final touches on XGBoost
- Train model until 2006
- Draw a sketch for the dashboard
